---
- name: Test NXOS
  hosts: hosts
  
  vars:
  cli:
    username: admin_mlu6
    password: cbcdj123!
    transport: cli

  nxos_command:
    commands: 
          - show version
          - show interfaces 
    provider: "{{ cli }}"
    
