---
- name: Hello World!
  hosts: all
  vars_files:
    - group_vars/vars.yml
    - group_vars/vault.yml
 
  tasks:
  
  - name: Print Hello World!
    shell: echo "{{ vault_secret }}"
    #debug: var="{{ secret }}"
