- name: Configure provider
  connection: local
  provider:
      host: "{{ inventory_hostname }}"
      transport: cli

- hosts: all
- name:  Start Run adhoc commands
  tasks:
   - name: Loop through commands
     ios_command:
        commands:  "{{ item }}"
        provider: "{{ provider }}"
     with_items: "{{ commands }}"
