--- 
- 
  ios_command: 
    commands: "{{ item }}"
    provider: "{{ provider }}"
  name: "Run adhoc commands"
  with_items: "{{ commands }}"
  register: output
  
- name: display output
  debug: 
    var: output
