--- 
- 
  ios_command: 
    #commands: "{{ item }}"
    commands:
      - show version
    #ansible_connection: network_cli
    provider: "{{ provider }}"
    wait_for: result[0] contains IOS
  name: "Run adhoc commands"
  #with_items: "{{ commands }}"
  register: version
  
- name: display output
  debug: 
    var: version.stdout
