--- 
- 
  ios_command: 
    commands: "{{ item }}"
    #commands:
    #  - show version
   
    provider: "{{ provider }}"
    #wait_for: result[0] contains IOS
  name: "Run adhoc commands"
  with_items: "{{ command_list }}"
  register: cmd_output
  
- name: display output
  debug: 
    var: cmd_output.stdout_lines
