--- 
- name: set backup_path fact
  set_fact:
    backup_path: "{{ playbook_dir }}/backup"
    
- name: set backup_file fact
  set_fact:
    backup_file: "{{ backup_path }}/{{ inventory_hostname }}/command_output"
    
- name: create backup paths
  file:
    path: "{{ backup_path }}"
    state: directory
  run_once: yes
  delegate_to: localhost

- name: create backup paths
  file:
    path: "{{ backup_path }}/{{ inventory_hostname }}"
    state: directory
  delegate_to: localhost
  
- ios_command: 
    #commands: "{{ item.command_list }}"
    commands:
      "{{ item.command }}"
   
    provider: "{{ provider }}"
    #wait_for: result[0] contains IOS
  name: "Run adhoc commands"
  with_items: "{{ commands }}"
  register: cmd_output
  
#- name: display output
  #debug: 
    #var: cmd_output
 

- name: write backup to file
  copy:
    content: "{{ cmd_output }}"
    dest: "{{ backup_file }}"

- name: display backup_file path
  debug: var=cmd_output

#- name: Save full data to file
#    copy: content="{{ output }}" dest="~/Downloads/commands_{{ inventory_hostname }}-{{ts}}.json"
