--- 
- 
  ios_command: 
    #commands: "{{ item.command_list }}"
    commands:
      "{{ item.command }}"
   
    provider: "{{ provider }}"
    #wait_for: result[0] contains IOS
  name: "Run adhoc commands"
  with_items: "{{ commands }}"
  register: cmd_output
  
- name: display output
  debug: 
    var: cmd_output
