--- 
- 
  ios_command: 
    commands: "{{ item }}"
    #ansible_connection: network_cli
    provider: "{{ provider }}"
    wait_for: result[0] contains IOS
  name: "Run adhoc commands"
  with_items: "{{ commands }}"
  register: output
  
- name: display output
  debug: 
    var: output.stdout_lines
